package com.pay.national.agent.model.entity;

import java.util.Date;

public class AccessTokenManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.ID
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.STATUS
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.CREATE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.LAST_UPDATE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.EFFECT_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.EXPIRE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_manager.ACCESS_TOKEN
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    private String accessToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.ID
     *
     * @return the value of access_token_manager.ID
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.ID
     *
     * @param id the value for access_token_manager.ID
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.OPTIMISTIC
     *
     * @return the value of access_token_manager.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.OPTIMISTIC
     *
     * @param optimistic the value for access_token_manager.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.STATUS
     *
     * @return the value of access_token_manager.STATUS
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.STATUS
     *
     * @param status the value for access_token_manager.STATUS
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.CREATE_TIME
     *
     * @return the value of access_token_manager.CREATE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.CREATE_TIME
     *
     * @param createTime the value for access_token_manager.CREATE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.LAST_UPDATE_TIME
     *
     * @return the value of access_token_manager.LAST_UPDATE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for access_token_manager.LAST_UPDATE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.EFFECT_TIME
     *
     * @return the value of access_token_manager.EFFECT_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.EFFECT_TIME
     *
     * @param effectTime the value for access_token_manager.EFFECT_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.EXPIRE_TIME
     *
     * @return the value of access_token_manager.EXPIRE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.EXPIRE_TIME
     *
     * @param expireTime the value for access_token_manager.EXPIRE_TIME
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_manager.ACCESS_TOKEN
     *
     * @return the value of access_token_manager.ACCESS_TOKEN
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token_manager.ACCESS_TOKEN
     *
     * @param accessToken the value for access_token_manager.ACCESS_TOKEN
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }
}