package com.pay.national.agent.model.entity;

import java.util.Date;

public class AgentBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.ID
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String childBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.BUSINESS_NAME
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.STATUS
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.REWARD_AMOUNT
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private Double rewardAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.FEATURE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.REWARD_STANDARD
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String rewardStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.LINK
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.SHOW_INDEX
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private Integer showIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_business.CREATE_TIME
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.ID
     *
     * @return the value of agent_business.ID
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.ID
     *
     * @param id the value for agent_business.ID
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.OPTIMISTIC
     *
     * @return the value of agent_business.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.OPTIMISTIC
     *
     * @param optimistic the value for agent_business.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.CHILD_BUSINESS_CODE
     *
     * @return the value of agent_business.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getChildBusinessCode() {
        return childBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.CHILD_BUSINESS_CODE
     *
     * @param childBusinessCode the value for agent_business.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setChildBusinessCode(String childBusinessCode) {
        this.childBusinessCode = childBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.BUSINESS_CODE
     *
     * @return the value of agent_business.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.BUSINESS_CODE
     *
     * @param businessCode the value for agent_business.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.BUSINESS_NAME
     *
     * @return the value of agent_business.BUSINESS_NAME
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.BUSINESS_NAME
     *
     * @param businessName the value for agent_business.BUSINESS_NAME
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.STATUS
     *
     * @return the value of agent_business.STATUS
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.STATUS
     *
     * @param status the value for agent_business.STATUS
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.REWARD_AMOUNT
     *
     * @return the value of agent_business.REWARD_AMOUNT
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public Double getRewardAmount() {
        return rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.REWARD_AMOUNT
     *
     * @param rewardAmount the value for agent_business.REWARD_AMOUNT
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setRewardAmount(Double rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.FEATURE
     *
     * @return the value of agent_business.FEATURE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.FEATURE
     *
     * @param feature the value for agent_business.FEATURE
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.REWARD_STANDARD
     *
     * @return the value of agent_business.REWARD_STANDARD
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getRewardStandard() {
        return rewardStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.REWARD_STANDARD
     *
     * @param rewardStandard the value for agent_business.REWARD_STANDARD
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setRewardStandard(String rewardStandard) {
        this.rewardStandard = rewardStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.LINK
     *
     * @return the value of agent_business.LINK
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.LINK
     *
     * @param link the value for agent_business.LINK
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.SHOW_INDEX
     *
     * @return the value of agent_business.SHOW_INDEX
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.SHOW_INDEX
     *
     * @param showIndex the value for agent_business.SHOW_INDEX
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_business.CREATE_TIME
     *
     * @return the value of agent_business.CREATE_TIME
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_business.CREATE_TIME
     *
     * @param createTime the value for agent_business.CREATE_TIME
     *
     * @mbggenerated Tue Jan 23 20:26:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}