package com.pay.national.agent.model.entity;

import java.util.Date;

public class ApiTicketManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.ID
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.STATUS
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.CREATE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.LAST_UPDATE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.EFFECT_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.EXPIRE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_ticket_manager.API_TICKEt
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    private String apiTicket;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.ID
     *
     * @return the value of api_ticket_manager.ID
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.ID
     *
     * @param id the value for api_ticket_manager.ID
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.OPTIMISTIC
     *
     * @return the value of api_ticket_manager.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.OPTIMISTIC
     *
     * @param optimistic the value for api_ticket_manager.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.STATUS
     *
     * @return the value of api_ticket_manager.STATUS
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.STATUS
     *
     * @param status the value for api_ticket_manager.STATUS
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.CREATE_TIME
     *
     * @return the value of api_ticket_manager.CREATE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.CREATE_TIME
     *
     * @param createTime the value for api_ticket_manager.CREATE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.LAST_UPDATE_TIME
     *
     * @return the value of api_ticket_manager.LAST_UPDATE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for api_ticket_manager.LAST_UPDATE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.EFFECT_TIME
     *
     * @return the value of api_ticket_manager.EFFECT_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.EFFECT_TIME
     *
     * @param effectTime the value for api_ticket_manager.EFFECT_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.EXPIRE_TIME
     *
     * @return the value of api_ticket_manager.EXPIRE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.EXPIRE_TIME
     *
     * @param expireTime the value for api_ticket_manager.EXPIRE_TIME
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_ticket_manager.API_TICKEt
     *
     * @return the value of api_ticket_manager.API_TICKEt
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public String getApiTicket() {
        return apiTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_ticket_manager.API_TICKEt
     *
     * @param apiTicket the value for api_ticket_manager.API_TICKEt
     *
     * @mbggenerated Tue Jan 30 09:41:27 GMT+08:00 2018
     */
    public void setApiTicket(String apiTicket) {
        this.apiTicket = apiTicket;
    }
}