package com.pay.national.agent.model.entity;

import java.util.Date;

public class AppUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.ID
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.OPTIMISTIC
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.USER_NAME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.STATUS
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.PASSWORD
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.MAX_ERROR_TIMES
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Integer maxErrorTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.LAST_LOGIN_ERR_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Date lastLoginErrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.MODIFY_PASSWD_CYCLE
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Integer modifyPasswdCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.PASSWD_MODIFY_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Date passwdModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.ALLOW_BEGIN_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String allowBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.ALLOW_END_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String allowEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.REALNAME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.CREATE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.LAST_UPDATE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.PASSWD_EXPIRE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Date passwdExpireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.PASSWD_EFFECT_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private Date passwdEffectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.USER_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.PARENT_USER_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String parentUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.PHONE_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.EMAIL
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.IDENTITY_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String identityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.SOURCE
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.ABLE_STATUS
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    private String ableStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.ID
     *
     * @return the value of app_user.ID
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.ID
     *
     * @param id the value for app_user.ID
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.OPTIMISTIC
     *
     * @return the value of app_user.OPTIMISTIC
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.OPTIMISTIC
     *
     * @param optimistic the value for app_user.OPTIMISTIC
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.USER_NAME
     *
     * @return the value of app_user.USER_NAME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.USER_NAME
     *
     * @param userName the value for app_user.USER_NAME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.STATUS
     *
     * @return the value of app_user.STATUS
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.STATUS
     *
     * @param status the value for app_user.STATUS
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.PASSWORD
     *
     * @return the value of app_user.PASSWORD
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.PASSWORD
     *
     * @param password the value for app_user.PASSWORD
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.MAX_ERROR_TIMES
     *
     * @return the value of app_user.MAX_ERROR_TIMES
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Integer getMaxErrorTimes() {
        return maxErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.MAX_ERROR_TIMES
     *
     * @param maxErrorTimes the value for app_user.MAX_ERROR_TIMES
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setMaxErrorTimes(Integer maxErrorTimes) {
        this.maxErrorTimes = maxErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.LAST_LOGIN_ERR_TIME
     *
     * @return the value of app_user.LAST_LOGIN_ERR_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Date getLastLoginErrTime() {
        return lastLoginErrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.LAST_LOGIN_ERR_TIME
     *
     * @param lastLoginErrTime the value for app_user.LAST_LOGIN_ERR_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setLastLoginErrTime(Date lastLoginErrTime) {
        this.lastLoginErrTime = lastLoginErrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.MODIFY_PASSWD_CYCLE
     *
     * @return the value of app_user.MODIFY_PASSWD_CYCLE
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Integer getModifyPasswdCycle() {
        return modifyPasswdCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.MODIFY_PASSWD_CYCLE
     *
     * @param modifyPasswdCycle the value for app_user.MODIFY_PASSWD_CYCLE
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setModifyPasswdCycle(Integer modifyPasswdCycle) {
        this.modifyPasswdCycle = modifyPasswdCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.PASSWD_MODIFY_TIME
     *
     * @return the value of app_user.PASSWD_MODIFY_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Date getPasswdModifyTime() {
        return passwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.PASSWD_MODIFY_TIME
     *
     * @param passwdModifyTime the value for app_user.PASSWD_MODIFY_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setPasswdModifyTime(Date passwdModifyTime) {
        this.passwdModifyTime = passwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.ALLOW_BEGIN_TIME
     *
     * @return the value of app_user.ALLOW_BEGIN_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getAllowBeginTime() {
        return allowBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.ALLOW_BEGIN_TIME
     *
     * @param allowBeginTime the value for app_user.ALLOW_BEGIN_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setAllowBeginTime(String allowBeginTime) {
        this.allowBeginTime = allowBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.ALLOW_END_TIME
     *
     * @return the value of app_user.ALLOW_END_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getAllowEndTime() {
        return allowEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.ALLOW_END_TIME
     *
     * @param allowEndTime the value for app_user.ALLOW_END_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setAllowEndTime(String allowEndTime) {
        this.allowEndTime = allowEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.REALNAME
     *
     * @return the value of app_user.REALNAME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.REALNAME
     *
     * @param realname the value for app_user.REALNAME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.CREATE_TIME
     *
     * @return the value of app_user.CREATE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.CREATE_TIME
     *
     * @param createTime the value for app_user.CREATE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.LAST_UPDATE_TIME
     *
     * @return the value of app_user.LAST_UPDATE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for app_user.LAST_UPDATE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.PASSWD_EXPIRE_TIME
     *
     * @return the value of app_user.PASSWD_EXPIRE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Date getPasswdExpireTime() {
        return passwdExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.PASSWD_EXPIRE_TIME
     *
     * @param passwdExpireTime the value for app_user.PASSWD_EXPIRE_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setPasswdExpireTime(Date passwdExpireTime) {
        this.passwdExpireTime = passwdExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.PASSWD_EFFECT_TIME
     *
     * @return the value of app_user.PASSWD_EFFECT_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public Date getPasswdEffectTime() {
        return passwdEffectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.PASSWD_EFFECT_TIME
     *
     * @param passwdEffectTime the value for app_user.PASSWD_EFFECT_TIME
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setPasswdEffectTime(Date passwdEffectTime) {
        this.passwdEffectTime = passwdEffectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.USER_NO
     *
     * @return the value of app_user.USER_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.USER_NO
     *
     * @param userNo the value for app_user.USER_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.PARENT_USER_NO
     *
     * @return the value of app_user.PARENT_USER_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getParentUserNo() {
        return parentUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.PARENT_USER_NO
     *
     * @param parentUserNo the value for app_user.PARENT_USER_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setParentUserNo(String parentUserNo) {
        this.parentUserNo = parentUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.PHONE_NO
     *
     * @return the value of app_user.PHONE_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.PHONE_NO
     *
     * @param phoneNo the value for app_user.PHONE_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.EMAIL
     *
     * @return the value of app_user.EMAIL
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.EMAIL
     *
     * @param email the value for app_user.EMAIL
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.IDENTITY_NO
     *
     * @return the value of app_user.IDENTITY_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.IDENTITY_NO
     *
     * @param identityNo the value for app_user.IDENTITY_NO
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.SOURCE
     *
     * @return the value of app_user.SOURCE
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.SOURCE
     *
     * @param source the value for app_user.SOURCE
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.ABLE_STATUS
     *
     * @return the value of app_user.ABLE_STATUS
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public String getAbleStatus() {
        return ableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.ABLE_STATUS
     *
     * @param ableStatus the value for app_user.ABLE_STATUS
     *
     * @mbggenerated Mon Jan 29 17:12:37 GMT+08:00 2018
     */
    public void setAbleStatus(String ableStatus) {
        this.ableStatus = ableStatus;
    }
}