package com.pay.national.agent.model.entity;

public class BusinessExpantion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.ID
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.STATUS
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.COLUMN_CODE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private String columnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.COLUMN_NAME
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_expantion.COLUMN_VALUE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    private String columnValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.ID
     *
     * @return the value of business_expantion.ID
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.ID
     *
     * @param id the value for business_expantion.ID
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.OPTIMISTIC
     *
     * @return the value of business_expantion.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.OPTIMISTIC
     *
     * @param optimistic the value for business_expantion.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.STATUS
     *
     * @return the value of business_expantion.STATUS
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.STATUS
     *
     * @param status the value for business_expantion.STATUS
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.BUSINESS_CODE
     *
     * @return the value of business_expantion.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.BUSINESS_CODE
     *
     * @param businessCode the value for business_expantion.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.COLUMN_CODE
     *
     * @return the value of business_expantion.COLUMN_CODE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public String getColumnCode() {
        return columnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.COLUMN_CODE
     *
     * @param columnCode the value for business_expantion.COLUMN_CODE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setColumnCode(String columnCode) {
        this.columnCode = columnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.COLUMN_NAME
     *
     * @return the value of business_expantion.COLUMN_NAME
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.COLUMN_NAME
     *
     * @param columnName the value for business_expantion.COLUMN_NAME
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_expantion.COLUMN_VALUE
     *
     * @return the value of business_expantion.COLUMN_VALUE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public String getColumnValue() {
        return columnValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_expantion.COLUMN_VALUE
     *
     * @param columnValue the value for business_expantion.COLUMN_VALUE
     *
     * @mbggenerated Tue Jan 23 20:28:09 CST 2018
     */
    public void setColumnValue(String columnValue) {
        this.columnValue = columnValue;
    }
}