package com.pay.national.agent.model.entity;

import java.util.Date;

/**
 * @author shuyan.qi
 */
public class BusinessRewardRule extends BaseEntity{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.business_code
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.parent_business_code
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private String parentBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.status
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.reward_type
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private String rewardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.reward_amount
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private Double rewardAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.rwward_proportion
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private Double rewardProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.create_time
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_reward_rule.last_update_time
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.business_code
     *
     * @return the value of business_reward_rule.business_code
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.business_code
     *
     * @param businessCode the value for business_reward_rule.business_code
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.parent_business_code
     *
     * @return the value of business_reward_rule.parent_business_code
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public String getParentBusinessCode() {
        return parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.parent_business_code
     *
     * @param parentBusinessCode the value for business_reward_rule.parent_business_code
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setParentBusinessCode(String parentBusinessCode) {
        this.parentBusinessCode = parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.status
     *
     * @return the value of business_reward_rule.status
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.status
     *
     * @param status the value for business_reward_rule.status
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.reward_type
     *
     * @return the value of business_reward_rule.reward_type
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public String getRewardType() {
        return rewardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.reward_type
     *
     * @param rewardType the value for business_reward_rule.reward_type
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setRewardType(String rewardType) {
        this.rewardType = rewardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.reward_amount
     *
     * @return the value of business_reward_rule.reward_amount
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public Double getRewardAmount() {
        return rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.reward_amount
     *
     * @param rewardAmount the value for business_reward_rule.reward_amount
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setRewardAmount(Double rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.rwward_proportion
     *
     * @return the value of business_reward_rule.rwward_proportion
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public Double getRewardProportion() {
        return rewardProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.rwward_proportion
     *
     * @param rewardProportion the value for business_reward_rule.rwward_proportion
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setRewardProportion(Double rewardProportion) {
        this.rewardProportion = rewardProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.create_time
     *
     * @return the value of business_reward_rule.create_time
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.create_time
     *
     * @param createTime the value for business_reward_rule.create_time
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_reward_rule.last_update_time
     *
     * @return the value of business_reward_rule.last_update_time
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_reward_rule.last_update_time
     *
     * @param lastUpdateTime the value for business_reward_rule.last_update_time
     *
     * @mbggenerated Wed Jan 24 22:39:24 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Override
    public String toString() {
        return super.toString()+"BusinessRewardRule{" +
                "businessCode='" + businessCode + '\'' +
                ", parentBusinessCode='" + parentBusinessCode + '\'' +
                ", status='" + status + '\'' +
                ", rewardType='" + rewardType + '\'' +
                ", rewardAmount=" + rewardAmount +
                ", rewardProportion=" + rewardProportion +
                ", createTime=" + createTime +
                ", lastUpdateTime=" + lastUpdateTime +
                '}';
    }
}