package com.pay.national.agent.model.entity;

import java.util.Date;

/**
 *
 * @author shuyan.qi
 */
public class BusinessOrder extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.user_no
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String userNo;

    private String openId;//微信用户公众号访问唯一凭证

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.business_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.business_code
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.parent_business_code
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String parentBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.status
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.customer_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.customer_phone
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.reward_amount
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private Double rewardAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.trans_amount
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private Double transAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.partner_business_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String partnerBusinessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.partner_business_no
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private String partnerBusinessNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.CREATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_order.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.user_no
     *
     * @return the value of business_order.user_no
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.user_no
     *
     * @param userNo the value for business_order.user_no
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.business_name
     *
     * @return the value of business_order.business_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.business_name
     *
     * @param businessName the value for business_order.business_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.business_code
     *
     * @return the value of business_order.business_code
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.business_code
     *
     * @param businessCode the value for business_order.business_code
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    @Override
    public String toString() {
        return super.toString()+"BusinessOrder{" +
                "userNo='" + userNo + '\'' +
                ", openId='" + openId + '\'' +
                ", businessName='" + businessName + '\'' +
                ", businessCode='" + businessCode + '\'' +
                ", parentBusinessCode='" + parentBusinessCode + '\'' +
                ", status='" + status + '\'' +
                ", customerName='" + customerName + '\'' +
                ", customerPhone='" + customerPhone + '\'' +
                ", rewardAmount=" + rewardAmount +
                ", transAmount=" + transAmount +
                ", partnerBusinessName='" + partnerBusinessName + '\'' +
                ", partnerBusinessNo='" + partnerBusinessNo + '\'' +
                ", createTime=" + createTime +
                ", lastUpdateTime=" + lastUpdateTime +
                '}';
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.parent_business_code
     *
     * @return the value of business_order.parent_business_code
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getParentBusinessCode() {
        return parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.parent_business_code
     *
     * @param parentBusinessCode the value for business_order.parent_business_code
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setParentBusinessCode(String parentBusinessCode) {
        this.parentBusinessCode = parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.status
     *
     * @return the value of business_order.status
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.status
     *
     * @param status the value for business_order.status
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.customer_name
     *
     * @return the value of business_order.customer_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.customer_name
     *
     * @param customerName the value for business_order.customer_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.customer_phone
     *
     * @return the value of business_order.customer_phone
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.customer_phone
     *
     * @param customerPhone the value for business_order.customer_phone
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.reward_amount
     *
     * @return the value of business_order.reward_amount
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public Double getRewardAmount() {
        return rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.reward_amount
     *
     * @param rewardAmount the value for business_order.reward_amount
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setRewardAmount(Double rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.trans_amount
     *
     * @return the value of business_order.trans_amount
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public Double getTransAmount() {
        return transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.trans_amount
     *
     * @param transAmount the value for business_order.trans_amount
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setTransAmount(Double transAmount) {
        this.transAmount = transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.partner_business_name
     *
     * @return the value of business_order.partner_business_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getPartnerBusinessName() {
        return partnerBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.partner_business_name
     *
     * @param partnerBusinessName the value for business_order.partner_business_name
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setPartnerBusinessName(String partnerBusinessName) {
        this.partnerBusinessName = partnerBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.partner_business_no
     *
     * @return the value of business_order.partner_business_no
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public String getPartnerBusinessNo() {
        return partnerBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.partner_business_no
     *
     * @param partnerBusinessNo the value for business_order.partner_business_no
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setPartnerBusinessNo(String partnerBusinessNo) {
        this.partnerBusinessNo = partnerBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.CREATE_TIME
     *
     * @return the value of business_order.CREATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.CREATE_TIME
     *
     * @param createTime the value for business_order.CREATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_order.LAST_UPDATE_TIME
     *
     * @return the value of business_order.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_order.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for business_order.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:38:52 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

}