package com.pay.national.agent.model.entity;

import java.util.Date;

public class CheckCodeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.ID
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.OPTIMISTIC
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.ABLE_STATUS
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private String ableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.USER_NO
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.OPEN_ID
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.PHONE_NO
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.CREATE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.LAST_UPDATE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.EFFECT_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.EXPIRE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code_info.CODE
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.ID
     *
     * @return the value of check_code_info.ID
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.ID
     *
     * @param id the value for check_code_info.ID
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.OPTIMISTIC
     *
     * @return the value of check_code_info.OPTIMISTIC
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.OPTIMISTIC
     *
     * @param optimistic the value for check_code_info.OPTIMISTIC
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.ABLE_STATUS
     *
     * @return the value of check_code_info.ABLE_STATUS
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public String getAbleStatus() {
        return ableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.ABLE_STATUS
     *
     * @param ableStatus the value for check_code_info.ABLE_STATUS
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setAbleStatus(String ableStatus) {
        this.ableStatus = ableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.USER_NO
     *
     * @return the value of check_code_info.USER_NO
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.USER_NO
     *
     * @param userNo the value for check_code_info.USER_NO
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.OPEN_ID
     *
     * @return the value of check_code_info.OPEN_ID
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.OPEN_ID
     *
     * @param openId the value for check_code_info.OPEN_ID
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.PHONE_NO
     *
     * @return the value of check_code_info.PHONE_NO
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.PHONE_NO
     *
     * @param phoneNo the value for check_code_info.PHONE_NO
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.CREATE_TIME
     *
     * @return the value of check_code_info.CREATE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.CREATE_TIME
     *
     * @param createTime the value for check_code_info.CREATE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.LAST_UPDATE_TIME
     *
     * @return the value of check_code_info.LAST_UPDATE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for check_code_info.LAST_UPDATE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.EFFECT_TIME
     *
     * @return the value of check_code_info.EFFECT_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.EFFECT_TIME
     *
     * @param effectTime the value for check_code_info.EFFECT_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.EXPIRE_TIME
     *
     * @return the value of check_code_info.EXPIRE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.EXPIRE_TIME
     *
     * @param expireTime the value for check_code_info.EXPIRE_TIME
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code_info.CODE
     *
     * @return the value of check_code_info.CODE
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code_info.CODE
     *
     * @param code the value for check_code_info.CODE
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    public void setCode(String code) {
        this.code = code;
    }
}