package com.pay.national.agent.model.entity;

import java.util.Date;

public class CreditCardUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.id
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.optimistic
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.user_name
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.phone_no
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.business_code
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.parent_business_code
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private String parentBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.status
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.create_time
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.last_update_time
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.id
     *
     * @return the value of credit_card_user.id
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.id
     *
     * @param id the value for credit_card_user.id
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.optimistic
     *
     * @return the value of credit_card_user.optimistic
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.optimistic
     *
     * @param optimistic the value for credit_card_user.optimistic
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.user_name
     *
     * @return the value of credit_card_user.user_name
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.user_name
     *
     * @param userName the value for credit_card_user.user_name
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.phone_no
     *
     * @return the value of credit_card_user.phone_no
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.phone_no
     *
     * @param phoneNo the value for credit_card_user.phone_no
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.business_code
     *
     * @return the value of credit_card_user.business_code
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.business_code
     *
     * @param businessCode the value for credit_card_user.business_code
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.parent_business_code
     *
     * @return the value of credit_card_user.parent_business_code
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public String getParentBusinessCode() {
        return parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.parent_business_code
     *
     * @param parentBusinessCode the value for credit_card_user.parent_business_code
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setParentBusinessCode(String parentBusinessCode) {
        this.parentBusinessCode = parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.status
     *
     * @return the value of credit_card_user.status
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.status
     *
     * @param status the value for credit_card_user.status
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.create_time
     *
     * @return the value of credit_card_user.create_time
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.create_time
     *
     * @param createTime the value for credit_card_user.create_time
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.last_update_time
     *
     * @return the value of credit_card_user.last_update_time
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.last_update_time
     *
     * @param lastUpdateTime the value for credit_card_user.last_update_time
     *
     * @mbggenerated Sat Mar 17 17:36:18 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}