package com.pay.national.agent.model.entity;

import java.util.Date;

public class CreditCardUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.ID
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.OPTIMISTIC
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.USER_NAME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.PHONE_NO
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private String childBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.BUSINESS_CODE
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.STATUS
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.CREATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_card_user.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.ID
     *
     * @return the value of credit_card_user.ID
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.ID
     *
     * @param id the value for credit_card_user.ID
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.OPTIMISTIC
     *
     * @return the value of credit_card_user.OPTIMISTIC
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.OPTIMISTIC
     *
     * @param optimistic the value for credit_card_user.OPTIMISTIC
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.USER_NAME
     *
     * @return the value of credit_card_user.USER_NAME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.USER_NAME
     *
     * @param userName the value for credit_card_user.USER_NAME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.PHONE_NO
     *
     * @return the value of credit_card_user.PHONE_NO
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.PHONE_NO
     *
     * @param phoneNo the value for credit_card_user.PHONE_NO
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.CHILD_BUSINESS_CODE
     *
     * @return the value of credit_card_user.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public String getChildBusinessCode() {
        return childBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.CHILD_BUSINESS_CODE
     *
     * @param childBusinessCode the value for credit_card_user.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setChildBusinessCode(String childBusinessCode) {
        this.childBusinessCode = childBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.BUSINESS_CODE
     *
     * @return the value of credit_card_user.BUSINESS_CODE
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.BUSINESS_CODE
     *
     * @param businessCode the value for credit_card_user.BUSINESS_CODE
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.STATUS
     *
     * @return the value of credit_card_user.STATUS
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.STATUS
     *
     * @param status the value for credit_card_user.STATUS
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.CREATE_TIME
     *
     * @return the value of credit_card_user.CREATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.CREATE_TIME
     *
     * @param createTime the value for credit_card_user.CREATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_card_user.LAST_UPDATE_TIME
     *
     * @return the value of credit_card_user.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_card_user.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for credit_card_user.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}