package com.pay.national.agent.model.entity;

import java.util.Date;

public class MenuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.ID
     *
     * @mbggenerated Mon Jan 29 11:40:10 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.OPTIMISTIC
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MENU_NO
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String menuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MENU_NAME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.WX_MENU_URL
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String wxMenuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.REDIRECT_MENU_URL
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String redirectMenuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MENU_KEY
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String menuKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.PARENT_ID
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MENU_ORDER
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MENU_TYPE
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MENU_VERSION
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String menuVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.STATUS
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.CREATE_TIME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.REMARK
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.ID
     *
     * @return the value of menu_info.ID
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.ID
     *
     * @param id the value for menu_info.ID
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.OPTIMISTIC
     *
     * @return the value of menu_info.OPTIMISTIC
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.OPTIMISTIC
     *
     * @param optimistic the value for menu_info.OPTIMISTIC
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MENU_NO
     *
     * @return the value of menu_info.MENU_NO
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getMenuNo() {
        return menuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MENU_NO
     *
     * @param menuNo the value for menu_info.MENU_NO
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setMenuNo(String menuNo) {
        this.menuNo = menuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MENU_NAME
     *
     * @return the value of menu_info.MENU_NAME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MENU_NAME
     *
     * @param menuName the value for menu_info.MENU_NAME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.WX_MENU_URL
     *
     * @return the value of menu_info.WX_MENU_URL
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getWxMenuUrl() {
        return wxMenuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.WX_MENU_URL
     *
     * @param wxMenuUrl the value for menu_info.WX_MENU_URL
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setWxMenuUrl(String wxMenuUrl) {
        this.wxMenuUrl = wxMenuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.REDIRECT_MENU_URL
     *
     * @return the value of menu_info.REDIRECT_MENU_URL
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getRedirectMenuUrl() {
        return redirectMenuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.REDIRECT_MENU_URL
     *
     * @param redirectMenuUrl the value for menu_info.REDIRECT_MENU_URL
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setRedirectMenuUrl(String redirectMenuUrl) {
        this.redirectMenuUrl = redirectMenuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MENU_KEY
     *
     * @return the value of menu_info.MENU_KEY
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getMenuKey() {
        return menuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MENU_KEY
     *
     * @param menuKey the value for menu_info.MENU_KEY
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setMenuKey(String menuKey) {
        this.menuKey = menuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.PARENT_ID
     *
     * @return the value of menu_info.PARENT_ID
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.PARENT_ID
     *
     * @param parentId the value for menu_info.PARENT_ID
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MENU_ORDER
     *
     * @return the value of menu_info.MENU_ORDER
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MENU_ORDER
     *
     * @param menuOrder the value for menu_info.MENU_ORDER
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MENU_TYPE
     *
     * @return the value of menu_info.MENU_TYPE
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MENU_TYPE
     *
     * @param menuType the value for menu_info.MENU_TYPE
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MENU_VERSION
     *
     * @return the value of menu_info.MENU_VERSION
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getMenuVersion() {
        return menuVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MENU_VERSION
     *
     * @param menuVersion the value for menu_info.MENU_VERSION
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setMenuVersion(String menuVersion) {
        this.menuVersion = menuVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.STATUS
     *
     * @return the value of menu_info.STATUS
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.STATUS
     *
     * @param status the value for menu_info.STATUS
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.CREATE_TIME
     *
     * @return the value of menu_info.CREATE_TIME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.CREATE_TIME
     *
     * @param createTime the value for menu_info.CREATE_TIME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.MODIFY_TIME
     *
     * @return the value of menu_info.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.MODIFY_TIME
     *
     * @param modifyTime the value for menu_info.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.REMARK
     *
     * @return the value of menu_info.REMARK
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.REMARK
     *
     * @param remark the value for menu_info.REMARK
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}