package com.pay.national.agent.model.entity;

import java.util.Date;

/**
 * 奖励记录
 * @author shuyan.qi
 */
public class RewardRecord extends  BaseEntity{

    private static final long serialVersionUID = 8656159664536494857L;
    /**
     * 业务编码
     */
    private String businessCode;

    /**
     * 父业务编码
     */
    private String parentBusinessCode;

    /**
     *用户编号
     */
    private String userNo;

    /**
     * 奖励金额
     */
    private Double amount;

    /**
     * 状态
     */
    private String status;

    /**
     * 奖励时间
     */
    private Date rewardTime;

    /**
     * 错误代码
     */
    private String errorCode;

    /**
     * 错误信息
     */
    private String errorMsg;

    /**
     * 订单id
     */
    private Long orderId;

    /**
     * 奖励规则id
     */
    private Long ruleId;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     * 最后更新时间
     */
    private Date lastUpdateTime;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.business_code
     *
     * @return the value of reward_record.business_code
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.business_code
     *
     * @param businessCode the value for reward_record.business_code
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.parent_business_code
     *
     * @return the value of reward_record.parent_business_code
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public String getParentBusinessCode() {
        return parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.parent_business_code
     *
     * @param parentBusinessCode the value for reward_record.parent_business_code
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setParentBusinessCode(String parentBusinessCode) {
        this.parentBusinessCode = parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.user_no
     *
     * @return the value of reward_record.user_no
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.user_no
     *
     * @param userNo the value for reward_record.user_no
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.amount
     *
     * @return the value of reward_record.amount
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.amount
     *
     * @param amount the value for reward_record.amount
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.status
     *
     * @return the value of reward_record.status
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.status
     *
     * @param status the value for reward_record.status
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.reward_time
     *
     * @return the value of reward_record.reward_time
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public Date getRewardTime() {
        return rewardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.reward_time
     *
     * @param rewardTime the value for reward_record.reward_time
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setRewardTime(Date rewardTime) {
        this.rewardTime = rewardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.error_code
     *
     * @return the value of reward_record.error_code
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.error_code
     *
     * @param errorCode the value for reward_record.error_code
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.error_msg
     *
     * @return the value of reward_record.error_msg
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.error_msg
     *
     * @param errorMsg the value for reward_record.error_msg
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.order_id
     *
     * @return the value of reward_record.order_id
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.order_id
     *
     * @param orderId the value for reward_record.order_id
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.rule_id
     *
     * @return the value of reward_record.rule_id
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.rule_id
     *
     * @param ruleId the value for reward_record.rule_id
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.create_time
     *
     * @return the value of reward_record.create_time
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.create_time
     *
     * @param createTime the value for reward_record.create_time
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_record.last_update_time
     *
     * @return the value of reward_record.last_update_time
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_record.last_update_time
     *
     * @param lastUpdateTime the value for reward_record.last_update_time
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Override
    public String toString() {
        return super.toString()+"RewardRecord{" +
                "businessCode='" + businessCode + '\'' +
                ", parentBusinessCode='" + parentBusinessCode + '\'' +
                ", userNo='" + userNo + '\'' +
                ", amount=" + amount +
                ", status='" + status + '\'' +
                ", rewardTime=" + rewardTime +
                ", errorCode='" + errorCode + '\'' +
                ", errorMsg='" + errorMsg + '\'' +
                ", orderId=" + orderId +
                ", ruleId=" + ruleId +
                ", createTime=" + createTime +
                ", lastUpdateTime=" + lastUpdateTime +
                '}';
    }
}