package com.pay.national.agent.model.entity;

import java.util.Date;

/**
 * @author shuyan.qi
 */
public class RewardGather  extends BaseEntity{

    private static final long serialVersionUID = -4305268884417078477L;
    /**
     * 用户编号
     */
    private String userNo;

    /**
     * 业务编码
     */
    private String businessCode;

    /**
     * 父业务编码
     */
    private String parentBusinessCode;

    /**
     * 奖励总金额
     */
    private Double totalAmount;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后更新时间
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather.user_no
     *
     * @return the value of reward_gather.user_no
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather.user_no
     *
     * @param userNo the value for reward_gather.user_no
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather.business_code
     *
     * @return the value of reward_gather.business_code
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather.business_code
     *
     * @param businessCode the value for reward_gather.business_code
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather.parent_business_code
     *
     * @return the value of reward_gather.parent_business_code
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public String getParentBusinessCode() {
        return parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather.parent_business_code
     *
     * @param parentBusinessCode the value for reward_gather.parent_business_code
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public void setParentBusinessCode(String parentBusinessCode) {
        this.parentBusinessCode = parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather.total_amount
     *
     * @return the value of reward_gather.total_amount
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather.total_amount
     *
     * @param totalAmount the value for reward_gather.total_amount
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather.create_time
     *
     * @return the value of reward_gather.create_time
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather.create_time
     *
     * @param createTime the value for reward_gather.create_time
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather.last_update_time
     *
     * @return the value of reward_gather.last_update_time
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather.last_update_time
     *
     * @param lastUpdateTime the value for reward_gather.last_update_time
     *
     * @mbggenerated Thu Jan 25 11:38:25 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Override
    public String toString() {
        return super.toString()+"RewardGather{" +
                "userNo='" + userNo + '\'' +
                ", businessCode='" + businessCode + '\'' +
                ", parentBusinessCode='" + parentBusinessCode + '\'' +
                ", totalAmount=" + totalAmount +
                ", createTime=" + createTime +
                ", lastUpdateTime=" + lastUpdateTime +
                '}';
    }
}