package com.pay.national.agent.model.entity;

import java.util.Date;

/**
 * @author shuyan.qi
 */
public class RewardGatherMonth extends BaseEntity{
    private static final long serialVersionUID = 6629789468525748032L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.user_no
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.business_code
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.parent_business_code
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private String parentBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.total_amount
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private Double totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private Date month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.create_time
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.last_update_time
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.user_no
     *
     * @return the value of reward_gather_month.user_no
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.user_no
     *
     * @param userNo the value for reward_gather_month.user_no
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.business_code
     *
     * @return the value of reward_gather_month.business_code
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.business_code
     *
     * @param businessCode the value for reward_gather_month.business_code
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.parent_business_code
     *
     * @return the value of reward_gather_month.parent_business_code
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public String getParentBusinessCode() {
        return parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.parent_business_code
     *
     * @param parentBusinessCode the value for reward_gather_month.parent_business_code
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setParentBusinessCode(String parentBusinessCode) {
        this.parentBusinessCode = parentBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.total_amount
     *
     * @return the value of reward_gather_month.total_amount
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.total_amount
     *
     * @param totalAmount the value for reward_gather_month.total_amount
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.month
     *
     * @return the value of reward_gather_month.month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.month
     *
     * @param month the value for reward_gather_month.month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setMonth(Date month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.create_time
     *
     * @return the value of reward_gather_month.create_time
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.create_time
     *
     * @param createTime the value for reward_gather_month.create_time
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.last_update_time
     *
     * @return the value of reward_gather_month.last_update_time
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.last_update_time
     *
     * @param lastUpdateTime the value for reward_gather_month.last_update_time
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Override
    public String toString() {
        return super.toString()+"RewardGatherMonth{" +
                "userNo='" + userNo + '\'' +
                ", businessCode='" + businessCode + '\'' +
                ", parentBusinessCode='" + parentBusinessCode + '\'' +
                ", totalAmount=" + totalAmount +
                ", month=" + month +
                ", createTime=" + createTime +
                ", lastUpdateTime=" + lastUpdateTime +
                '}';
    }
}