package com.pay.national.agent.model.entity;

import java.util.Date;

public class RewardGatherMonth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.ID
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.USER_NO
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private String businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private String childBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.REWARD_AMOUNT_TOTAL
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private Double rewardAmountTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.REWARD_MONTH
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private String rewardMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_gather_month.CREATE_TIME
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.ID
     *
     * @return the value of reward_gather_month.ID
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.ID
     *
     * @param id the value for reward_gather_month.ID
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.OPTIMISTIC
     *
     * @return the value of reward_gather_month.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.OPTIMISTIC
     *
     * @param optimistic the value for reward_gather_month.OPTIMISTIC
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.USER_NO
     *
     * @return the value of reward_gather_month.USER_NO
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.USER_NO
     *
     * @param userNo the value for reward_gather_month.USER_NO
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.BUSINESS_CODE
     *
     * @return the value of reward_gather_month.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.BUSINESS_CODE
     *
     * @param businessCode the value for reward_gather_month.BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.CHILD_BUSINESS_CODE
     *
     * @return the value of reward_gather_month.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public String getChildBusinessCode() {
        return childBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.CHILD_BUSINESS_CODE
     *
     * @param childBusinessCode the value for reward_gather_month.CHILD_BUSINESS_CODE
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setChildBusinessCode(String childBusinessCode) {
        this.childBusinessCode = childBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.REWARD_AMOUNT_TOTAL
     *
     * @return the value of reward_gather_month.REWARD_AMOUNT_TOTAL
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public Double getRewardAmountTotal() {
        return rewardAmountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.REWARD_AMOUNT_TOTAL
     *
     * @param rewardAmountTotal the value for reward_gather_month.REWARD_AMOUNT_TOTAL
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setRewardAmountTotal(Double rewardAmountTotal) {
        this.rewardAmountTotal = rewardAmountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.REWARD_MONTH
     *
     * @return the value of reward_gather_month.REWARD_MONTH
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public String getRewardMonth() {
        return rewardMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.REWARD_MONTH
     *
     * @param rewardMonth the value for reward_gather_month.REWARD_MONTH
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setRewardMonth(String rewardMonth) {
        this.rewardMonth = rewardMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_gather_month.CREATE_TIME
     *
     * @return the value of reward_gather_month.CREATE_TIME
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_gather_month.CREATE_TIME
     *
     * @param createTime the value for reward_gather_month.CREATE_TIME
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}