package com.pay.national.agent.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WxPayBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.ID
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.PARTNER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String partnerTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.PAYMENT_NO
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String paymentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.OPENID
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.NONCE_STR
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String nonceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.CHECK_NAME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String checkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.RE_USER_NAME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String reUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.AMOUNT
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.DESC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.DESCRIPTION
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.IP
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.RETURN_MSG
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String returnMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.ERR_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String errCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.ERR_CODE_DESC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String errCodeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.PAYMENT_TIME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_bill.REMARK
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.ID
     *
     * @return the value of wx_pay_bill.ID
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.ID
     *
     * @param id the value for wx_pay_bill.ID
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.OPTIMISTIC
     *
     * @return the value of wx_pay_bill.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.OPTIMISTIC
     *
     * @param optimistic the value for wx_pay_bill.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.PARTNER_TRADE_NO
     *
     * @return the value of wx_pay_bill.PARTNER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getPartnerTradeNo() {
        return partnerTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.PARTNER_TRADE_NO
     *
     * @param partnerTradeNo the value for wx_pay_bill.PARTNER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setPartnerTradeNo(String partnerTradeNo) {
        this.partnerTradeNo = partnerTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.PAYMENT_NO
     *
     * @return the value of wx_pay_bill.PAYMENT_NO
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getPaymentNo() {
        return paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.PAYMENT_NO
     *
     * @param paymentNo the value for wx_pay_bill.PAYMENT_NO
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setPaymentNo(String paymentNo) {
        this.paymentNo = paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.OPENID
     *
     * @return the value of wx_pay_bill.OPENID
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.OPENID
     *
     * @param openid the value for wx_pay_bill.OPENID
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.NONCE_STR
     *
     * @return the value of wx_pay_bill.NONCE_STR
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.NONCE_STR
     *
     * @param nonceStr the value for wx_pay_bill.NONCE_STR
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.CHECK_NAME
     *
     * @return the value of wx_pay_bill.CHECK_NAME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getCheckName() {
        return checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.CHECK_NAME
     *
     * @param checkName the value for wx_pay_bill.CHECK_NAME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setCheckName(String checkName) {
        this.checkName = checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.RE_USER_NAME
     *
     * @return the value of wx_pay_bill.RE_USER_NAME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getReUserName() {
        return reUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.RE_USER_NAME
     *
     * @param reUserName the value for wx_pay_bill.RE_USER_NAME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setReUserName(String reUserName) {
        this.reUserName = reUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.AMOUNT
     *
     * @return the value of wx_pay_bill.AMOUNT
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.AMOUNT
     *
     * @param amount the value for wx_pay_bill.AMOUNT
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.DESC
     *
     * @return the value of wx_pay_bill.DESC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.DESC
     *
     * @param desc the value for wx_pay_bill.DESC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.DESCRIPTION
     *
     * @return the value of wx_pay_bill.DESCRIPTION
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.DESCRIPTION
     *
     * @param description the value for wx_pay_bill.DESCRIPTION
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.IP
     *
     * @return the value of wx_pay_bill.IP
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.IP
     *
     * @param ip the value for wx_pay_bill.IP
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.RETURN_CODE
     *
     * @return the value of wx_pay_bill.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.RETURN_CODE
     *
     * @param returnCode the value for wx_pay_bill.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.RETURN_MSG
     *
     * @return the value of wx_pay_bill.RETURN_MSG
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.RETURN_MSG
     *
     * @param returnMsg the value for wx_pay_bill.RETURN_MSG
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.RESULT_CODE
     *
     * @return the value of wx_pay_bill.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.RESULT_CODE
     *
     * @param resultCode the value for wx_pay_bill.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.ERR_CODE
     *
     * @return the value of wx_pay_bill.ERR_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.ERR_CODE
     *
     * @param errCode the value for wx_pay_bill.ERR_CODE
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.ERR_CODE_DESC
     *
     * @return the value of wx_pay_bill.ERR_CODE_DESC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getErrCodeDesc() {
        return errCodeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.ERR_CODE_DESC
     *
     * @param errCodeDesc the value for wx_pay_bill.ERR_CODE_DESC
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setErrCodeDesc(String errCodeDesc) {
        this.errCodeDesc = errCodeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.PAYMENT_TIME
     *
     * @return the value of wx_pay_bill.PAYMENT_TIME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.PAYMENT_TIME
     *
     * @param paymentTime the value for wx_pay_bill.PAYMENT_TIME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.CREATE_TIME
     *
     * @return the value of wx_pay_bill.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.CREATE_TIME
     *
     * @param createTime the value for wx_pay_bill.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_bill.REMARK
     *
     * @return the value of wx_pay_bill.REMARK
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_pay_bill.REMARK
     *
     * @param remark the value for wx_pay_bill.REMARK
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}