package com.pay.national.agent.model.entity;

import java.util.Date;

public class WxPublicPayDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.ID
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.OUTER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String outerTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.RETURN_MSG
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String returnMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.ERR_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String errCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.ERR_CODE_DES
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String errCodeDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.BUSI_TYPE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_detail.REMARK
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    private String remark;

    public WxPublicPayDetail() {
    }

    public WxPublicPayDetail(String outerTradeNo, String returnCode, String returnMsg, String resultCode,
                             String errCode, String errCodeDes, String busiType, String remark) {
        super();
        this.outerTradeNo = outerTradeNo;
        this.returnCode = returnCode;
        this.returnMsg = returnMsg;
        this.resultCode = resultCode;
        this.errCode = errCode;
        this.errCodeDes = errCodeDes;
        this.busiType = busiType;
        this.remark = remark;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.ID
     *
     * @return the value of wx_public_pay_detail.ID
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.ID
     *
     * @param id the value for wx_public_pay_detail.ID
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.OPTIMISTIC
     *
     * @return the value of wx_public_pay_detail.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.OPTIMISTIC
     *
     * @param optimistic the value for wx_public_pay_detail.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.OUTER_TRADE_NO
     *
     * @return the value of wx_public_pay_detail.OUTER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getOuterTradeNo() {
        return outerTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.OUTER_TRADE_NO
     *
     * @param outerTradeNo the value for wx_public_pay_detail.OUTER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setOuterTradeNo(String outerTradeNo) {
        this.outerTradeNo = outerTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.RETURN_CODE
     *
     * @return the value of wx_public_pay_detail.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.RETURN_CODE
     *
     * @param returnCode the value for wx_public_pay_detail.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.RETURN_MSG
     *
     * @return the value of wx_public_pay_detail.RETURN_MSG
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.RETURN_MSG
     *
     * @param returnMsg the value for wx_public_pay_detail.RETURN_MSG
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.RESULT_CODE
     *
     * @return the value of wx_public_pay_detail.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.RESULT_CODE
     *
     * @param resultCode the value for wx_public_pay_detail.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.ERR_CODE
     *
     * @return the value of wx_public_pay_detail.ERR_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.ERR_CODE
     *
     * @param errCode the value for wx_public_pay_detail.ERR_CODE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.ERR_CODE_DES
     *
     * @return the value of wx_public_pay_detail.ERR_CODE_DES
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.ERR_CODE_DES
     *
     * @param errCodeDes the value for wx_public_pay_detail.ERR_CODE_DES
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.BUSI_TYPE
     *
     * @return the value of wx_public_pay_detail.BUSI_TYPE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.BUSI_TYPE
     *
     * @param busiType the value for wx_public_pay_detail.BUSI_TYPE
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.CREATE_TIME
     *
     * @return the value of wx_public_pay_detail.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.CREATE_TIME
     *
     * @param createTime the value for wx_public_pay_detail.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_detail.REMARK
     *
     * @return the value of wx_public_pay_detail.REMARK
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_detail.REMARK
     *
     * @param remark the value for wx_public_pay_detail.REMARK
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}