package com.pay.national.agent.model.entity;

import java.util.Date;

public class WxPublicPayBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.PREPAY_BILL_ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Long prepayBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.OUTER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private String outerTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.TRANSACTION_ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.BANK_TYPE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.TOTAL_FEE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Integer totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.TIME_END
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Date timeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.MODIFY_TIME
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_public_pay_bill.REMARK
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    private String remark;

    public WxPublicPayBill(Long prepayBillId, String outerTradeNo, String transactionId, String returnCode,
                           String resultCode, String bankType, Integer totalFee, Date timeEnd, String remark) {
        super();
        this.prepayBillId = prepayBillId;
        this.outerTradeNo = outerTradeNo;
        this.transactionId = transactionId;
        this.returnCode = returnCode;
        this.resultCode = resultCode;
        this.bankType = bankType;
        this.totalFee = totalFee;
        this.timeEnd = timeEnd;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.ID
     *
     * @return the value of wx_public_pay_bill.ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.ID
     *
     * @param id the value for wx_public_pay_bill.ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.OPTIMISTIC
     *
     * @return the value of wx_public_pay_bill.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.OPTIMISTIC
     *
     * @param optimistic the value for wx_public_pay_bill.OPTIMISTIC
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.PREPAY_BILL_ID
     *
     * @return the value of wx_public_pay_bill.PREPAY_BILL_ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Long getPrepayBillId() {
        return prepayBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.PREPAY_BILL_ID
     *
     * @param prepayBillId the value for wx_public_pay_bill.PREPAY_BILL_ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setPrepayBillId(Long prepayBillId) {
        this.prepayBillId = prepayBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.OUTER_TRADE_NO
     *
     * @return the value of wx_public_pay_bill.OUTER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public String getOuterTradeNo() {
        return outerTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.OUTER_TRADE_NO
     *
     * @param outerTradeNo the value for wx_public_pay_bill.OUTER_TRADE_NO
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setOuterTradeNo(String outerTradeNo) {
        this.outerTradeNo = outerTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.TRANSACTION_ID
     *
     * @return the value of wx_public_pay_bill.TRANSACTION_ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.TRANSACTION_ID
     *
     * @param transactionId the value for wx_public_pay_bill.TRANSACTION_ID
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.RETURN_CODE
     *
     * @return the value of wx_public_pay_bill.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.RETURN_CODE
     *
     * @param returnCode the value for wx_public_pay_bill.RETURN_CODE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.RESULT_CODE
     *
     * @return the value of wx_public_pay_bill.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.RESULT_CODE
     *
     * @param resultCode the value for wx_public_pay_bill.RESULT_CODE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.BANK_TYPE
     *
     * @return the value of wx_public_pay_bill.BANK_TYPE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.BANK_TYPE
     *
     * @param bankType the value for wx_public_pay_bill.BANK_TYPE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setBankType(String bankType) {
        this.bankType = bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.TOTAL_FEE
     *
     * @return the value of wx_public_pay_bill.TOTAL_FEE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.TOTAL_FEE
     *
     * @param totalFee the value for wx_public_pay_bill.TOTAL_FEE
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.TIME_END
     *
     * @return the value of wx_public_pay_bill.TIME_END
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.TIME_END
     *
     * @param timeEnd the value for wx_public_pay_bill.TIME_END
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.CREATE_TIME
     *
     * @return the value of wx_public_pay_bill.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.CREATE_TIME
     *
     * @param createTime the value for wx_public_pay_bill.CREATE_TIME
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.MODIFY_TIME
     *
     * @return the value of wx_public_pay_bill.MODIFY_TIME
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.MODIFY_TIME
     *
     * @param modifyTime the value for wx_public_pay_bill.MODIFY_TIME
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_public_pay_bill.REMARK
     *
     * @return the value of wx_public_pay_bill.REMARK
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_public_pay_bill.REMARK
     *
     * @param remark the value for wx_public_pay_bill.REMARK
     *
     * @mbggenerated Sun Jan 28 11:25:01 GMT+08:00 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}