package com.pay.national.agent.core.dao.wx;

import com.pay.national.agent.model.entity.AccessTokenManager;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

public interface AccessTokenManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_manager
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_manager
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    int insert(AccessTokenManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_manager
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    int insertSelective(AccessTokenManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_manager
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    AccessTokenManager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_manager
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(AccessTokenManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_manager
     *
     * @mbggenerated Tue Jan 16 18:43:57 GMT+08:00 2018
     */
    int updateByPrimaryKey(AccessTokenManager record);

    AccessTokenManager findAccessTokenByTime(@Param("dateTime") Date date);
}