package com.pay.national.agent.core.dao.wx;

import com.pay.national.agent.model.entity.MenuInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    int insert(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    int insertSelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    MenuInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Mon Jan 29 11:40:11 GMT+08:00 2018
     */
    int updateByPrimaryKey(MenuInfo record);

    /**
     * 通过menuNo查询menu信息
     * @param menuNo
     * @return
     */
    MenuInfo findMenuInfoByMenuNo(@Param("menuNo") String menuNo);

    /**
     * 查询所有的父菜单
     * @return
     */
    List<MenuInfo> findFatherMenu();

    /**
     * 查询所有的子菜单
     * @param id
     * @return
     */
    List<MenuInfo> findChildMenuInfo(@Param("id") Long id);
}