package com.pay.national.agent.core.dao.wx;

import com.pay.national.agent.model.entity.QrCodeInfo;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

public interface QrCodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code_info
     *
     * @mbggenerated Mon Jan 29 15:02:42 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code_info
     *
     * @mbggenerated Mon Jan 29 15:02:42 GMT+08:00 2018
     */
    int insert(QrCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code_info
     *
     * @mbggenerated Mon Jan 29 15:02:42 GMT+08:00 2018
     */
    int insertSelective(QrCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code_info
     *
     * @mbggenerated Mon Jan 29 15:02:42 GMT+08:00 2018
     */
    QrCodeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code_info
     *
     * @mbggenerated Mon Jan 29 15:02:42 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(QrCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code_info
     *
     * @mbggenerated Mon Jan 29 15:02:42 GMT+08:00 2018
     */
    int updateByPrimaryKey(QrCodeInfo record);

    /**
     * 通过openId和时间查询当前生效的ticket
     * @param openId
     * @param date
     * @return
     */
    QrCodeInfo findTicketByOpenIdAndDate(@Param("openId") String openId, @Param("date") Date date);
}