package com.pay.national.agent.core.dao.wx;

import com.pay.national.agent.model.entity.WxPayBill;
import org.apache.ibatis.annotations.Param;

public interface WxPayBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_bill
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_bill
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    int insert(WxPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_bill
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    int insertSelective(WxPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_bill
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    WxPayBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_bill
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(WxPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_bill
     *
     * @mbggenerated Sun Jan 28 11:24:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(WxPayBill record);

    /**
     * 通过订单号查询企业付款订单信息
     * @param orderNo
     * @return
     */
    WxPayBill findPayBillByPartnerTradeNo(@Param("orderNo") String orderNo);
}