package com.pay.national.agent.core.dao.wx;

import com.pay.national.agent.model.entity.WxPublicPayDetail;

public interface WxPublicPayDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_pay_detail
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_pay_detail
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    int insert(WxPublicPayDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_pay_detail
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    int insertSelective(WxPublicPayDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_pay_detail
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    WxPublicPayDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_pay_detail
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(WxPublicPayDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_pay_detail
     *
     * @mbggenerated Sun Jan 28 14:24:46 GMT+08:00 2018
     */
    int updateByPrimaryKey(WxPublicPayDetail record);
}