package com.pay.national.agent.core.dao.wx;

import com.pay.national.agent.model.entity.WxPublicPrepayBill;
import org.apache.ibatis.annotations.Param;

public interface WxPublicPrepayBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_prepay_bill
     *
     * @mbggenerated Sun Jan 28 11:25:11 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_prepay_bill
     *
     * @mbggenerated Sun Jan 28 11:25:11 GMT+08:00 2018
     */
    int insert(WxPublicPrepayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_prepay_bill
     *
     * @mbggenerated Sun Jan 28 11:25:11 GMT+08:00 2018
     */
    int insertSelective(WxPublicPrepayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_prepay_bill
     *
     * @mbggenerated Sun Jan 28 11:25:11 GMT+08:00 2018
     */
    WxPublicPrepayBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_prepay_bill
     *
     * @mbggenerated Sun Jan 28 11:25:11 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(WxPublicPrepayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_public_prepay_bill
     *
     * @mbggenerated Sun Jan 28 11:25:11 GMT+08:00 2018
     */
    int updateByPrimaryKey(WxPublicPrepayBill record);

    /**
     * 通过商户订单号查询微信支付预付单信息
     * @param outerTradeNo
     * @return
     */
    WxPublicPrepayBill findWxPublicPrepayByOuterTradeNo(@Param("outerTradeNo") String outerTradeNo);
}