package com.pay.national.agent.core.dao.common;

import com.pay.national.agent.model.entity.CheckCodeInfo;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

public interface CheckCodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code_info
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code_info
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    int insert(CheckCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code_info
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    int insertSelective(CheckCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code_info
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    CheckCodeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code_info
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(CheckCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code_info
     *
     * @mbggenerated Fri Mar 02 09:43:35 GMT+08:00 2018
     */
    int updateByPrimaryKey(CheckCodeInfo record);


    CheckCodeInfo getEffectCheckCode(@Param("openId") String openId, @Param("phoneNo") String phoneNo, @Param("dateTime") Date date);
}