package com.pay.national.agent.core.dao.common;

import com.pay.national.agent.model.entity.CreditCardUser;

public interface CreditCardUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_card_user
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_card_user
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    int insert(CreditCardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_card_user
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    int insertSelective(CreditCardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_card_user
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    CreditCardUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_card_user
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(CreditCardUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_card_user
     *
     * @mbggenerated Wed Jan 24 22:39:09 CST 2018
     */
    int updateByPrimaryKey(CreditCardUser record);
}