package com.pay.national.agent.core.dao.common;

import com.pay.national.agent.core.bean.result.MonthRewardGatherBean;
import com.pay.national.agent.model.entity.RewardGatherMonth;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface RewardGatherMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    int insert(RewardGatherMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    int insertSelective(RewardGatherMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    RewardGatherMonth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    int updateByPrimaryKeySelective(RewardGatherMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Thu Jan 25 19:21:31 CST 2018
     */
    int updateByPrimaryKey(RewardGatherMonth record);

    List<MonthRewardGatherBean> group1(@Param("userNo") String userNo, @Param("startDate") Date startDate, @Param("endDate") Date endDate);

    List<MonthRewardGatherBean> group2(@Param("userNo") String userNo, @Param("parentBusinessCode") String parentBusinessCode, @Param("startDate") Date startDate, @Param("endDate") Date endDate);

    RewardGatherMonth selectByMonth(@Param("month") Date month, @Param("businessCode")String businessCode,@Param("userNo") String userNo);
}