package com.pay.national.agent.core.dao.common;

import com.pay.national.agent.model.entity.RewardGatherMonth;

public interface RewardGatherMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    int insert(RewardGatherMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    int insertSelective(RewardGatherMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    RewardGatherMonth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    int updateByPrimaryKeySelective(RewardGatherMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_month
     *
     * @mbggenerated Tue Jan 23 20:42:49 CST 2018
     */
    int updateByPrimaryKey(RewardGatherMonth record);
}