package com.pay.national.agent.core.dao.common;

import com.pay.national.agent.model.entity.RewardRecord;

public interface RewardRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_record
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_record
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    int insert(RewardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_record
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    int insertSelective(RewardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_record
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    RewardRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_record
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    int updateByPrimaryKeySelective(RewardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_record
     *
     * @mbggenerated Thu Jan 25 11:38:14 CST 2018
     */
    int updateByPrimaryKey(RewardRecord record);
}