package com.pay.national.agent.core.dao.common;

import com.pay.national.agent.core.bean.result.DayRewardGatherBean;
import com.pay.national.agent.model.entity.RewardGatherDay;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface RewardGatherDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_day
     *
     * @mbggenerated Thu Jan 25 19:21:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_day
     *
     * @mbggenerated Thu Jan 25 19:21:15 CST 2018
     */
    int insert(RewardGatherDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_day
     *
     * @mbggenerated Thu Jan 25 19:21:15 CST 2018
     */
    int insertSelective(RewardGatherDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_day
     *
     * @mbggenerated Thu Jan 25 19:21:15 CST 2018
     */
    RewardGatherDay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_day
     *
     * @mbggenerated Thu Jan 25 19:21:15 CST 2018
     */
    int updateByPrimaryKeySelective(RewardGatherDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_gather_day
     *
     * @mbggenerated Thu Jan 25 19:21:15 CST 2018
     */
    int updateByPrimaryKey(RewardGatherDay record);

    List<DayRewardGatherBean> group1(@Param("userNo") String userNo, @Param("startDate") Date startDate, @Param("endDate") Date endDate);

    List<DayRewardGatherBean> group2(@Param("userNo") String userNo, @Param("parentBusinessCode") String parentBusinessCode, @Param("startDate") Date startDate, @Param("endDate") Date endDate);

    void summary(@Param("userNo") String userNo,@Param("startDate")String startDate,@Param("endDate")String endDate);

    List<RewardGatherDay> selectByRewardDay(@Param("day") Date day, @Param("userNo") String userNo);
}